export enum ActionTypes {
  Login = '[AUTH COMPONENT] Login',
  Logout = '[AUTH COMPONENT] Logout',
  Toggle_Theme = '[THEME] TOGGLE THEME APP',
  Change_lang_app = '[LANGAUE] CHANGE LANGAUGE APP',
  Store_keywords_search = '[RECOMMENDED] STORE KEYWORDS SEARCH',
  Store_user_info = '[AUTH] STORE USER INFO',
  Set_module_page = '[APP] SET MODULE AND PAGE',
  Store_skill_history = '[RECOMMENCED JOB] STORE SKILL HISTORY',
  Set_user_permissions = '[AUTH] SET USER PERMISSIONS',
  Store_user_setting = '[USER-SETTING] STORE USER SETTING',
  Store_user_id = '[USER] STORE USER ID',
  Store_user_profile = '[USER PROFILE] STORE USER PROFILE',
  Change_company_app = '[COMPANY] CHANGE COMPANY',
  Change_reload_data_flag = '[APP] CHANGE RELOAD DATA FLAG',
  Get_data_reload_flag = '[APP] GET DATA RELOAD FLAG',
  Loading_app = '[APP] APP LOADING',
  Show_snackbar = '[APP] SHOW SNACKBAR',
  isReloadApiConfig = '[APP] RELOAD API CONFIG',
  Get_object_id_webdb = '[WEB DB] GET OBJECT ID WEBDB',
  Get_currency_symbol = '[APP] GET CURRENCY SYMBOL',
  remmember_me = '[APP] REMMEMBER ME',
  get_caption_by_pages = '[APP] GET CAPTIONS BY PAGES',
  get_common_caption = '[APP] GET COMMON CAPTION',
  get_page_info = '[APP] GET PAGE INFO',
  get_common_message = '[APP] GET COMMON MESSAGES',
  get_environment = '[APP] GET ENVIRONMENT'
}

//TODO camel case for all lines
